### PR TITLE
Generated atsr.py file is python3 compliant.

### PR DESCRIPTION
**Pull request by mdavis36**
This PR fixes the generated atsr.py file and makes is python3 compliant.
- imports all of argparse for use of `Namespace`.
- converts python2 dictionary access to python3 syntax.

### CODE REVIEW

**Comment by dawson6** [comment]
I'll vet this tomorrow @mdavis36 , am hot ont something else just now.

**Review by dawson6 — APPROVED** [review]
Passed my tests.

**Comment by mdavis36** [comment]
Please leave this branch open until the next release we are pointing our spack installation here.

**Comment by dawson6** [comment]
Will do

**Pull request merged**
