### PR TITLE
Adding jsrun_np_max option

### PR DESCRIPTION
**Pull request by MishaZakharchanka**
Adds options that are similar to the existing jsrun_np and lsrun_np options, but with additional logic to only override the np set for tests if the np is larger than the number provided to these options. This way tests that are meant to run on less processors than specified aren't moved to higher counts.t

This PR will close: https://github.com/LLNL/ATS/issues/94

### CODE REVIEW

**Comment by MishaZakharchanka** [comment]
Would like to do more testing. I'll move this out of a Draft after said testing is done.

**Comment by dawson6** [comment]
BTW, the test scenario is likely one where the np_max option was not specified on the command line

**Comment by MishaZakharchanka** [comment]
@dawson6 if you could run a few tests on this it would be much appreciated. The few tests that I have seem to be working but they aren't very extensive. Seems to be working with Kripke.

**Comment by dawson6** [comment]
Will do, testing again\

**Review by dawson6 — APPROVED** [review]

**Comment by dawson6** [comment]
OK, I am awake today, and this all looks good.
going to merge it for you @MishaZakharchanka

**Pull request merged**
