### PR TITLE
Command line option to overwrite all time limits

### PR DESCRIPTION
**Pull request by MishaZakharchanka**
This PR allows the command line option "--cutoff" to override any time limit set (in ATS file or command line) if it is set.

This PR will close: https://github.com/LLNL/ATS/issues/104

### CODE REVIEW

**Comment by dawson6** [comment]
See related issue for discussion.

We need to make 'flux' work the same as slurm and LSF with respect to processing --cutoff and --timeout.  Currently flux yanks the credentials at the timelimit and the job is just marked as 'failed' but it would be better to put this in the timeout category.

**Comment by dawson6** [comment]
Thursday, 2023 March 16. Shawn is testing again after MR updates.  Stay tuned.

**Comment by dawson6** [comment]
flux:--------------------------------------------------------

This initial run has no time limits specivied in the test.ats file
So it will use the default of 29m.

atsflux test.ats (All tests should PASS)
ATS SUMMARY March 16, 2023 06:30:44
FAILED:  0
PASSED:   220

atsflux test.ats --cutoff 10s (should have 4-6 TIMEOUTS)
ATS SUMMARY March 16, 2023 06:32:24
FAILED:  0
TIMEOUT:  12 kripke...
PASSED:   196
SKIPPED:  12

atsflux test.ats --cutoff 2s (should have 20+ TIMEOUTS)
ATS SUMMARY March 16, 2023 06:35:17
FAILED:  0
TIMEOUT:  49 ...
PASSED:   122
SKIPPED:  49


(hmm, more than with slurm, but still reasonable, hang on may be not, i just recalled something)
Dang it, I think we *do* have to use the flux timeout option! 

Will discuss why this is in the related ISSUE, but basically, there can be a long
overlap between the time we tell flux to start the job and when it actually starts
the job.  Flux can handel over-requests better than slurm or lsf, so we have to 
rely on flux to handle the time limits, as we want to eventually give flux *all* the jobs
at the outset and remove ATS throttling of test submissions!

**Comment by MishaZakharchanka** [comment]
I think there's something more going on here, @dawson6, that I've been trying to track down today, but haven't been able to nail yet. 

I've written a very simple ATS file for myself to test with two simple .cpp files: one that sleeps for 10sec and returns, the other sleeps for 30sec and returns. When I run this ATS file with no arguments on Flux one of the tests (the longer one) finishes with a TIMEOUT, the other passes as excepted. When I have the "-t" option code in fluxScheduled.py setting --timelimit has the same result, even if the time should be enough to run both tests ("45s" for example). When using the --cutoff option though, everything works correctly (returning TIMEOUT status and all).

I commented out the "-t" option code and ran with the --timelimit option set to different values and then it works correctly, just like --cutoff. Although running with no timing options still has a TIMEOUT.

I will keep digging, but would be interested to see if you are seeing the same thing that I am, because this seems to differ from what you reported previously and I would like to make sure we are on the same page.

**Pull request merged**
