### PR TITLE
Swapping results from management main to return 0 on success and 1 on error

### PR DESCRIPTION
**Pull request by dawson6**
redoing merge request with changes

### CODE REVIEW

**Comment by dawson6** [comment]
Very confused, my checkout of this shows '0' but the MR 'diffs' shows False still.

**Comment by dawson6** [comment]
hang on, may not have pushed <doh!>

**Comment by dawson6** [comment]
ok, fixed, I thought I had pushed my update, but it was uncommitted. So committed, rebased, and pushed again,

**Comment by white238** [comment]
Alternate suggestion:

`ATSManager.main()` could continue to return True on success and False on failure

then change:

https://github.com/LLNL/ATS/blob/main/ats/__main__.py to return 0 on manager.main() success and 1 otherwise

This would allow downstream users who wrap `ATSManager` to check for success based on the boolean but the ultimate command line return code would follow standards.

**Pull request closed without merging**
